### ISSUE TITLE
PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'net.touchcapture.qr.flutterqr/qrview')

### ISSUE THREAD

**Issue by breederComrade** [juliuscanute/qr_code_scanner#39] opened 2019-09-14 13:33 UTC
add   <key>io.flutter.embedded_views_preview</key>
<true/>  

error 

~~~
Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'net.touchcapture.qr.flutterqr/qrview')
~~~
~~~
#362    Element.updateChild 
package:flutter/…/widgets/framework.dart:2876
#363    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:5099
#364    Element.updateChild 
package:flutter/…/widgets/framework.dart:2876
#365    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3935
#366    Element.rebuild 
package:flutter/…/widgets/framework.dart:3721
#367    StatefulElement.update 
package:flutter/…/widgets/framework.dart:4085
#368    Element.updateChild 
package:flutter/…/widgets/framework.dart:2876
#369    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:5099
#370    Element.updateChild 
package:flutter/…/widgets/framework.dart:2876
#371    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:5099
#372    Element.updateChild 
package:flutter/…/widgets/framework.dart:2876
#373    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3935
#374    Element.rebuild 
package:flutter/…/widgets/framework.dart:3721
#375    BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2340
#376    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:700
#377    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersis<…>
~~~~

**Comment by juliansteenbakker** [comment] 2020-12-10 18:18
As mentioned in #162 it seems to be working after a restart. Can you please make sure you cleaned your build folder and if the issue still persist run `flutter doctor -v` command and post the output here. I will close it for now since i cant seem to reproduce this error.

**Closed by juliansteenbakker** 2020-12-10 18:18 UTC

**Comment by karta0807913** [comment] 2021-05-22 09:40
Hi, I get the same problem on my flutter `Flutter 2.2.0` with `Dart 2.13.0`.
My solution to this problem is to modify the minSdkVersion in android/app/build.gradle.

This may be helpful!
