### ISSUE TITLE
[BUG] Unable to scan simple text qr code (image attached)

### ISSUE THREAD

**Issue by andyjriley** [juliuscanute/qr_code_scanner#266] opened 2021-02-17 00:14 UTC
**Describe the bug**
Working with a large set of qr codes which have a single number. However the scanner is not able to recognize the qr code and doesn't generate any error message in console.

**Flutter information**
Always provide the output of `flutter doctor -v` as it is needed in order to know on which Flutter versions the bug exists in.
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-US)
    • Flutter version 1.22.6 at /Users/andrewjriley/Developer/flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andrewjriley/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Pixel XL (mobile) • HT77L0204163 • android-arm64 • Android 10 (API 29)

**Device (please complete the following information):**
 - Device: Pixel XL
 - OS: Android 10 (API 29)

**Additional context**
(Attached Image)
![IMG_0498](https://user-images.githubusercontent.com/5934581/108138073-6eabb580-707a-11eb-84b0-37a8f8913a2a.JPG)
![IMG_0499](https://user-images.githubusercontent.com/5934581/108138083-710e0f80-707a-11eb-8e5c-919c1192a3a4.JPG)

**Comment by parthpatel5** [comment] 2021-03-04 12:13
Same problem.
![image](https://user-images.githubusercontent.com/39239666/109962335-137ff100-7d11-11eb-9afa-18128f26499d.png)
Pls resolve it asap.

**Comment by SilkeNL** [comment] 2021-03-09 14:20
Same problem here.
@juliuscanute

**Comment by 2shrestha22** [comment] 2021-04-12 01:25
> Same problem.
> ![image](https://user-images.githubusercontent.com/39239666/109962335-137ff100-7d11-11eb-9afa-18128f26499d.png)
> Pls resolve it asap.

It is scaned as Rohit only when camera is moved a little bit far.

**Comment by 2shrestha22** [comment] 2021-04-12 01:33
I can confirm that the QR by op is not scanned by Barcode App by ZXing Team, and also some popular app in PlayStore can't detect this QR. However Firebase ML Vision can detect it but slowly.

**Comment by juliansteenbakker** [comment] 2021-06-02 14:55
Since this is an issue with the framework thats being used, it will be fixed when switching to MLKit. Please follow #176 for progress.

**Closed by juliansteenbakker** 2021-06-02 14:55 UTC
Labels: bug

**Comment by chansdad** [comment] 2022-01-13 15:18
so I tried scanning simple text like 235 , which is encoded using some of the popular qr code generator sites , and the scan fails , but the same text if i chose the optoin of either url or phone etc , encoded perhaps in a diff format is being read just fine ,
