### ISSUE TITLE
Lower android embedding possible

### ISSUE THREAD

**Issue by felixwortmann** [juliuscanute/qr_code_scanner#158] opened 2020-11-16 19:32 UTC
In the README, it says you should use at least android sdk 24, which excludes about 20% of potential users due to androids os fragmentation. Is it possible in any way to lower this?

**Comment by juliansteenbakker** [comment] 2020-12-10 09:16
Duplicate of #123. Will try to fix this in first upcoming release.

**Closed by juliansteenbakker** 2020-12-10 09:16 UTC
Labels: duplicate
