### ISSUE TITLE
preview show black screen

### ISSUE THREAD

**Issue by KingWu** [juliuscanute/qr_code_scanner#159] opened 2020-11-22 03:49 UTC
i try the following navigation.

Scanner
--> push & replace new page
Home
-->  push & replace new page
Scanner

When go back to scanner, the camera preview show black screen.
and show the following message

```
I/CameraPreview(11505): Starting preview
D/CameraInstance(11505): Starting preview
D/CameraPreview(11505): resume()
W/CameraPreview(11505): initCamera called twice
D/CameraPreview(11505): resume()
W/CameraPreview(11505): initCamera called twice
D/CameraPreview(11505): resume()
W/CameraPreview(11505): initCamera called twice
```

Remarks: i just use the example code.

**Comment by Hebams** [comment] 2020-11-24 06:33
same issue when pause the application and resume it again

**Comment by apetroaeiandrei** [comment] 2020-11-26 10:56
Try to close the keyboard before navigating. This solved my black screen issue on Android. On iOS the area covered by the camera remained white.

**Comment by Hebams** [comment] 2020-12-01 11:17
> Try to close the keyboard before navigating. This solved my black screen issue on Android. On iOS the area covered by the keyboard remained white.
> FocusScope.of(context).unfocus(); - to close the keyboard

no keyboard in my screen

**Comment by x4080** [comment] 2020-12-06 00:41
I got the same result in IOS, not in android

**Comment by KamilSvoboda** [comment] 2020-12-10 16:57
> Try to close the keyboard before navigating. This solved my black screen issue on Android. On iOS the area covered by the keyboard remained white.
> FocusScope.of(context).unfocus(); - to close the keyboard

The issue is related with opened keyboard in my case. Unfortunately unfocus is not solution because I can't wait the moment the keyboard is closed, then start scanning. When I close the keyboard manually everything is OK.

**Comment by juliansteenbakker** [comment] 2020-12-17 08:47
Just to be clear: The issue persists on iOS when using the example application? I tried it just now but i could not reproduce this. Are you using version 0.1.0?

**Comment by EdsonBueno** [comment] 2020-12-22 21:42
The same happens here with the example project, but only on Android 10.
Nothing on iOS and nothing on Android 5 (the ones I could test it).
To reproduce it, simply lock/unlock the screen with the camera opened.

**Comment by cahix** [comment] 2020-12-29 16:50
i solved it by calling  pauseCamera(); resumeCamera() after navigating from a widget that would open the keyboard

**Comment by EdsonBueno** [comment] 2020-12-29 17:11
@cahix Have you tried lock and unlock the screen while on the camera screen?

**Comment by cahix** [comment] 2020-12-30 15:26
@EdsonBueno i do not have problems with that on my android device. it seems like it gets paused automatically when locking the screen. i am using version 0.1.0

**Comment by juliansteenbakker** [comment] 2021-01-11 22:31
I have released v0.3.0. Can someone please check if the problem still persists on that version?

**Comment by juliansteenbakker** [comment] 2021-01-12 19:51
When the keyboard opens, even on another page, it will cause a black screen unless you add `resizeToAvoidBottomInset = false` to the scaffold the qrview is in. That issue is described here #128. 

As for just navigating back and forward between pages, i couldn't encounter this behaviour with version 0.3.0.
If you still encounter this issue please feel free to comment. I'm closing this for now.

**Closed by juliansteenbakker** 2021-01-12 19:51 UTC
Labels: bug, question

**Comment by EdsonBueno** [comment] 2021-01-13 09:38
Still stops working on Android 10 if I lock and unlock the screen with the camera opened @juliansteenbakker

**Comment by chickahoona** [comment] 2021-01-13 11:14
Thanks @juliansteenbakker This was haunting me already for so long ... Should be part of the default example!

**Comment by mortifactor** [comment] 2021-02-07 09:18
https://user-images.githubusercontent.com/1426349/107142195-b2f2d380-695f-11eb-99c7-365c10ecabc2.mp4

Unfortunately still having this problem from time to time.
Tried pausing/resuming on qrview creating and "resizeToAvoidBottomInset = false". Nothing helped.

**Comment by juliansteenbakker** [comment] 2021-02-08 14:24
@mortifactor If you look closely to the dialog, you see it moving when the keyboard pops up. I think this is causing the black screen.
