### ISSUE TITLE
Device is getting incredibly hot

### ISSUE THREAD

**Issue by novas1r1** [juliuscanute/qr_code_scanner#81] opened 2020-03-29 10:23 UTC
Hi,
Has anyone else discovered the phone getting hot while scanning qrcodes? I need to scan a lot of them and camera stays open. After a few minutes my device (Pixel 2) gets hot as hell.

Cant get any information out of the logs so maybe someone knows whats wrong here.
Best regards
Verena

**Comment by Nomy1** [comment] 2020-04-08 04:05
It's most likely just a camera thing. It takes a lot of resources generating new images 30fps and putting it to the screen.

**Comment by juliansteenbakker** [comment] 2020-12-10 18:57
This is really device specific. A device can get hot since it's previewing the camera image and scanning for QR codes. Will close this for now since there isn't really a fix for it, and i haven't been able to reproduce this issue on several devices like a Galaxy S9+ or an iPad.

**Closed by juliansteenbakker** 2020-12-10 18:57 UTC
