### ISSUE TITLE
[FEATURE] Need a function that supports importing pictures to identify QR codes

### ISSUE THREAD

**Issue by Xutaotaotao** [juliuscanute/qr_code_scanner#175] opened 2020-12-15 02:43 UTC
**Is your feature request related to a problem? Please describe.**
Need a function that supports importing pictures to identify QR codes

**Describe the solution you'd like**
Need a function that supports importing pictures to identify QR codes

**Additional context**
Need a function that supports importing pictures to identify QR codes

**Comment by juliansteenbakker** [comment] 2020-12-21 19:47
Duplicate of #37

**Closed by juliansteenbakker** 2020-12-21 19:47 UTC
Labels: enhancement
