### ISSUE TITLE
Not work on Iphone12 [BUG] 

### ISSUE THREAD

**Issue by yarmel** [juliuscanute/qr_code_scanner#254] opened 2021-02-08 14:47 UTC
**Describe the bug**
The example code does not work on IOS12. The scanning area is wrong. Can scan only if use QRView without QrScannerOverlayShape.

**Flutter information**
Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-UA)

**Device (please complete the following information):**
 - Device: iPhone12
 - OS: iOS14.3

**Comment by thomaaam** [comment] 2021-02-08 19:29
@yarmel Do you also experience an initial zoom at 2x or 4x?
Then your issue might be the same as our issue: #250

**Comment by juliansteenbakker** [comment] 2021-02-08 20:42
Duplicate of #250. A fix is almost ready.

**Closed by juliansteenbakker** 2021-02-08 20:42 UTC
Labels: bug
