### ISSUE TITLE
Restrict Scanned barcode types

### ISSUE THREAD

**Issue by craigbrown-nist** [juliuscanute/qr_code_scanner#107] opened 2020-07-01 03:50 UTC
Is it/will it be possible to restrict barcode types to specific ones e.g.
  List<BarcodeFormat> selectedFormats = [BarcodeFormat.dataMatrix];

I cannot find a source that indicates how to do this, but it is possible for many barcode scanners.

**Comment by juliansteenbakker** [comment] 2020-12-21 21:42
Duplicate of #93.

**Closed by juliansteenbakker** 2020-12-21 21:42 UTC
