### ISSUE TITLE
AndroidX Error: Trying to create an already created platform view

### ISSUE THREAD

**Issue by jaddoescad** [juliuscanute/qr_code_scanner#62] opened 2019-12-16 21:52 UTC
Whenever I run the example for the first time, It works perfectly fine. As soon as i hot restart, I get the error below: (This only happens on Android, and it only started happening when i added android x to the project)

> E/flutter (24613): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view id: 0
E/flutter (24613):      at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
E/flutter (24613):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter (24613):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (24613):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (24613):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (24613):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (24613):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (24613):      at android.os.MessageQueue.next(MessageQueue.java:143)
E/flutter (24613):      at android.os.Looper.loop(Looper.java:130)
E/flutter (24613):      at android.app.ActivityThread.main(ActivityThread.java:6838)
E/flutter (24613):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (24613):      at java.lang.reflect.Method.invoke(Method.java:372)
E/flutter (24613):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/flutter (24613):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
E/flutter (24613): , null)
E/flutter (24613): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (24613): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (24613): <asynchronous suspension>
E/flutter (24613): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (24613): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (24613): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (24613): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (24613): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (24613): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24613): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (24613): #9      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (24613): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (24613): #11     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806:17)
E/flutter (24613): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (24613): #13     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (24613): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (24613): #15     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter (24613): #16     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (24613): #17     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter (24613): #18     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter (24613): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (24613): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24613): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (24613): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24613): #23     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
E/flutter (24613): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (24613): #25     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (24613): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (24613): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24613): #28     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
E/flutter (24613): #29     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
E/flutter (24613): #30     RendererBinding.drawFrame (package:flutter/src/r

**Comment by jamesncl** [comment] 2020-01-05 14:15
I have the same issue:

```
PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view id: 0
I/flutter (15038): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
I/flutter (15038): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
I/flutter (15038): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
I/flutter (15038): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
I/flutter (15038): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
I/flutter (15038): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
I/flutter (15038): 	at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (15038): 	at android.os.MessageQueue.next(MessageQueue.java:336)
I/flutter (15038): 	at android.os.Looper.loop(Looper.java:174)
I/flutter (15038): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
I/flutter (15038): 	at java.lang.reflect.Method.invoke(Nat
I/flutter (15038): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
I/flutter (15038): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
I/flutter (15038): <asynchronous suspension>
I/flutter (15038): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
I/flutter (15038): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
I/flutter (15038): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
I/flutter (15038): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
I/flutter (15038): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
I/flutter (15038): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (15038): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
I/flutter (15038): #9      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
I/flutter (15038): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:17
```

It only seems to happen after a hot restart, so I'm hoping this will not be an issue in production. There is a [similar issue with google_maps_flutter plugin](https://github.com/flutter/flutter/issues/45695). The problem may be with flutter itself, not with qr_code_scanner?

**Comment by novas1r1** [comment] 2020-03-25 12:01
Same issue with Google Pixel 2 using Flutter (Channel stable, v1.12.13+hotfix.5):

**Comment by mustakimpawle** [comment] 2020-04-20 11:58
Same issue.
Any update?

**Comment by dspicher** [comment] 2020-05-23 13:44
Can anyone of you try to reproduce the problem with Flutter 1.17?

**Comment by RenanDelfanti** [comment] 2020-08-27 18:44
Any update? Same error on Flutter 1.20

**Comment by juliansteenbakker** [comment] 2020-12-17 09:55
I can't reproduce this error. Please provide more information about the device using and post the output of `flutter doctor -v`. closing this for now.

**Closed by juliansteenbakker** 2020-12-17 09:55 UTC
Labels: bug
