### ISSUE TITLE
[FEATURE] Make text inside of QRView UIAlertView dialog customizable

### ISSUE THREAD

**Issue by FogelAO** [juliuscanute/qr_code_scanner#198] opened 2020-12-23 16:52 UTC
**By default if scanning is unavailable hardcoded value will be shown in dialog**
By default QRView will show UIAlertView with hardcoded text that scanning is un available (if it is). It will be strange if the app is localized
**I would like to make it customizable from Flutter side**
I think it will be nice if we could change this message from the Flutter when we initialize the widget

**Comment by juliansteenbakker** [comment] 2021-01-11 22:37
duplicate of #103

**Closed by juliansteenbakker** 2021-01-11 22:37 UTC
Labels: enhancement
