### ISSUE TITLE
[BUG][0.5.0+] Permission set is called before the user give/refuse permission

### ISSUE THREAD

**Issue by huberrom** [juliuscanute/qr_code_scanner#326] opened 2021-06-01 13:26 UTC
**Describe the bug**
It was working fine with the 0.4.0 version, but since the 0.5.0 verison, the callback for onPermissionSet is called before the user respond. In my app, it causes to have two pop up asking for the permission (one from the lib, then one from me). 
Only tried on Android yet, I can try on iOS if needed.

**Flutter information**
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [version 10.0.19042.985], locale fr-FR)
    • Flutter version 2.2.1 at C:\Users\RomainHuber\Workspace\Flutter\flutter
    • Framework revision 02c026b03c (5 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

**Device (please complete the following information):**
 - PCT L29 (mobile)  • android-arm64  • Android 10 (API 29)

**Comment by huberrom** [comment] 2021-06-01 14:08
So after trying on IOS, I do not reproduce the bug. Only on Android (Oneplus, Huawei, Sony)

**Comment by manhlh** [comment] 2021-06-02 07:23
Same error, when upload aab file on console, i received waring 
"Your APK or Android App Bundle is using permissions that require a privacy policy: (android.permission.CAMERA)"
screen shot: 
![image](https://user-images.githubusercontent.com/17887196/120440705-05904980-c3ae-11eb-82ab-fd73af7609f5.png)

**Comment by juliansteenbakker** [comment] 2021-06-02 14:41
> "Your APK or Android App Bundle is using permissions that require a privacy policy: (android.permission.CAMERA)"


> Enter your privacy policy url into playstore, see here Apps using these permissions in an APK (android.permission.GET_ACCOUNTS ) are required to have a *privacy policy* set

Source: https://stackoverflow.com/a/62882823/13031778

**Comment by huberrom** [comment] 2021-06-02 14:43
It's not the same problem as mine tho 🤔

**Comment by juliansteenbakker** [comment] 2021-06-02 15:24
I know, i'm looking into your issue however i'm unable to reproduce this behavior. Do you maybe have any test code?

**Comment by manhlh** [comment] 2021-06-02 15:46
Oh sorry, my problem is solved .

**Comment by huberrom** [comment] 2021-06-02 18:56
It's pretty simple :

`
class ScannerPage extends StatefulWidget {
  static const String route = "/scanner-page";

  @override
  _ScannerPageState createState() => _ScannerPageState();
}

class _ScannerPageState extends State<ScannerPage> with WidgetsBindingObserver {
  final GlobalKey qrKey = GlobalKey(debugLabel: 'QR');
  QRViewController? controller;
  bool hasOpenSettings = false;
  bool isDialogDisplayed = false;

  @override
  void initState() {
    WidgetsBinding.instance?.addObserver(this);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
              onWillPop: _onBackPressed,
              child: Scaffold(
                body: Column(
                  children: <Widget>[
                    Expanded(
                      flex: 5,
                      child: _stackMainBody(),
                    ),
                  ],
                ),
              ));
  }

  Widget _stackMainBody() {
    return Stack(alignment: Alignment.center, children: [
      _qrWidget(),
    ]);
  }

  Widget _qrWidget() {
    var scanArea = (MediaQuery.of(context).size.width < 400 ||
            MediaQuery.of(context).size.height < 400)
        ? 200.0
        : 315.0;
    double borderWith = 5;
    return QRView(
        key: qrKey,
        onQRViewCreated: _onQRViewCreated,
        onPermissionSet: _onPermissionSet,
        overlay: QrScannerOverlayShape(
            borderColor: Colors.white,
            overlayColor: Colors.black87,
            borderRadius: 10,
            borderLength: scanArea / 2 + borderWith * 2,
            borderWidth: borderWith,
            cutOutSize: scanArea));
  }

  void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    controller.scannedDataStream.listen((scanData) {
          //Do something with scan
      });
  }

  void _onPermissionSet(QRViewController controller, bool hasBeenAccepted) {
    if (!hasBeenAccepted) {
      _displayDialogPermission();
    }
  }

  void _displayDialogPermission() {
    showDialog(
        context: context,
        barrierDismissible: false,
        builder: (BuildContext context) => CupertinoAlertDialog(
              title: Text('Camera Permission'),
              content: Text(
                  'Cette application a besoin d\'accéder à la caméra pour scanner et filmer'),
              actions: <Widget>[
                CupertinoDialogAction(
                    child: Text('Refuser'),
                    onPressed: () => _refuseToChangeSettings()),
                CupertinoDialogAction(
                  child: Text('Settings'),
                  onPressed: () => _acceptToChangeSettings(),
                ),
              ],
            ));
  }

  Future<bool> _onBackPressed() async {
    SystemChannels.platform.invokeMethod<void>('SystemNavigator.pop');
    return false;
  }

  void _refuseToChangeSettings() {
    SystemChannels.platform.invokeMethod<void>('SystemNavigator.pop');
  }

  void _acceptToChangeSettings() async {
    hasOpenSettings = true;
    openAppSettings();
    Navigator.of(context, rootNavigator: true).pop("Settings");
  }
  
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed && hasOpenSettings) {
      hasOpenSettings = false;
      Permission.camera.isGranted.then((hasBeenGranted) => {
            if (!hasBeenGranted) {_displayDialogPermission()}
          });
    }
  }

  @override
  void dispose() {
    WidgetsBinding.instance?.removeObserver(this);
    controller?.dispose();
    super.dispose();
  }
}`

**Comment by kuhnroyal** [comment] 2021-06-24 15:11
Having a similar problem. I think the source of this is that `_startScan` is called right away when the view is constructed, before there is a chance to respond to missing permissions.

**Comment by juliansteenbakker** [comment] 2021-07-16 08:07
I have merged #351 which changes some things to the permission handling. Can you please try again with the master branch?

**Comment by huberrom** [comment] 2021-07-16 08:45
Looks like it's working on Android now. Do you need me to test on IOS ?

**Comment by juliansteenbakker** [comment] 2021-07-19 07:24
I have released all changes with v0.5.2 so i am closing this now. I don't think iOS ever suffered from this problem.

**Closed by juliansteenbakker** 2021-07-19 07:24 UTC
Labels: bug, on hold

**Comment by VaishvikaPawar** [comment] 2022-07-07 10:46
I tried the above mentioned solution but it did not work for me.
I just added a line in _onPermissionSet function and it is working for me. Someone please tell me if it's right way or not.

void _onPermissionSet(BuildContext context, QRViewController ctrl, bool p) {
      log('${DateTime.now().toIso8601String()}_onPermissionSet $p');
      if (!p) {
          ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('no Permission')),
          );
      }
      **controller!.resumeCamera();**
  }
