### ISSUE TITLE
scan area become black when cursor placed in textfield and scan does not work

### ISSUE THREAD

**Issue by kprathap23** [juliuscanute/qr_code_scanner#83] opened 2020-04-11 11:56 UTC
![Screenshot_2020-04-10-21-27-21-087](https://user-images.githubusercontent.com/2254065/79042930-62182e80-7c19-11ea-83b1-1b6a16d48612.jpg)

**Comment by kprathap23** [comment] 2020-04-11 11:59
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';

class Flutter_Scanner_1 extends StatefulWidget {
  @override
  _Flutter_Scanner_1State createState() => _Flutter_Scanner_1State();
}

class _Flutter_Scanner_1State extends State<Flutter_Scanner_1> {

  var _txtSerialNoController = new TextEditingController();

  final GlobalKey qrKey = GlobalKey(debugLabel: 'QR');
  var qrText = "";
  QRViewController controller;



  @override
  void initState() {
    // TODO: implement initState
    super.initState();


  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(

      child: Scaffold(

        appBar: AppBar(
          title: Text('Scanner 1'),
        ),

        body: Container(
          padding: EdgeInsets.all(8),
          child: Column(
            children: <Widget>[
              TextFormField(
                controller: _txtSerialNoController,
                textInputAction: TextInputAction.done,
                keyboardType: TextInputType.text,
                autofocus: false,
                decoration: InputDecoration(
                  border: new OutlineInputBorder(
                      borderSide: BorderSide(
                        width: 0.5,
                      ),
                      borderRadius: BorderRadius.all(Radius.circular(5.0))),
                  filled: true,
                  fillColor: Colors.white,
                  hintText: 'Enter Serial number',
                  contentPadding: EdgeInsets.fromLTRB(12.0, 12.0, 12.0, 12.0),
                ),

              ),


               Container(
                 height: 5,
               )
              ,


               Expanded(

                 flex: 1,
                 child: QRView(
                   key: qrKey,
                   onQRViewCreated: _onQRViewCreated,
                 ),
               ),




            ],

          ),
        ),
      ),




    );
  }

  void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;


    controller.scannedDataStream.listen((scanData) {
      setState(() {
        qrText = scanData;
        controller.pauseCamera();

        showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: Text(" Scan Result"),
            content: Container(
              width: double.maxFinite,
              child: Text("Scanned Barcode is" + scanData),
            ),
            actions: [
              new FlatButton(
                child: Text("OK"),
                onPressed: () {
                  Navigator.of(context).pop();
                  controller.resumeCamera();

                },
              ),
            ],
          ),
        );





      });
    });
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }



}

**Comment by WingCH** [comment] 2020-04-14 07:48
Duplicate of #68

**Closed** 2020-04-16 10:28 UTC
