### ISSUE TITLE
[FEATURE] Check currently active side of camera

### ISSUE THREAD

**Issue by mrgulshanyadav** [juliuscanute/qr_code_scanner#197] opened 2020-12-22 15:19 UTC
There in this library, I can't find a way to check if the front camera is opened or the rear is opened. We only have the option to switch between the front/back camera but not to check the current camera side.

**Comment by juliansteenbakker** [comment] 2020-12-22 15:29
With upcomming version 0.3.0 it will be possible to switch camera as follows:

```
QRView(
              key: qrKey,
              onQRViewCreated: _onQRViewCreated,
              cameraFacing: CameraFacing.front, // uses CameraFacing.back if nothing is supplied
            ),
```

I am still working on this release and i expect to finish this at the end of this week.
Also, this is a duplicate of #86

**Closed by juliansteenbakker** 2020-12-22 15:29 UTC
Labels: enhancement

**Comment by mrgulshanyadav** [comment] 2020-12-30 08:20
I am still eagerly waiting for this 😞

**Comment by juliansteenbakker** [comment] 2020-12-30 09:43
I have been busy during the holidays but its almost ready for release.

**Comment by mrgulshanyadav** [comment] 2020-12-30 09:47
thanks, @juliansteenbakker 😄 , please publish it ASAP, a project of mine is on hold because of this

**Comment by juliansteenbakker** [comment] 2020-12-30 15:09
[You can check the progress in this branch.](https://github.com/juliuscanute/qr_code_scanner/tree/86-select-camera-on-start) Be aware that this is work in progress and still needs some testing.
