### ISSUE TITLE
 if I keep the camera on the QR code and use pauseCamera, somtimes many received from listen not just one

### ISSUE THREAD

**Issue by jjjachyty** [juliuscanute/qr_code_scanner#78] opened 2020-03-28 15:19 UTC

**Comment by jjjachyty** [comment] 2020-03-28 15:26
This happens if I keep the camera on the QR code

**Comment by jaykon-w** [comment] 2020-06-04 20:18
use RxDart exhaustMap to send a timer to await camera to stop.

```dart
  void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    subscription = controller.scannedDataStream.exhaustMap((scanData) {
      if (_isDatamatrix(scanData)) {
        _datamatrixListen(scanData);
      } else {
        _barcodeListen(scanData);
      }
      return TimerStream(scanData, Duration(milliseconds: 200));
    }).listen(
      (_) {},
      onError: (error) => _showToast("Ocorreu um erro na leitura"),
    );
  }

  void _barcodeListen(String scanData) {
    try {
      this.controller.pauseCamera();
      print(scanData);
    } catch (err) {
      _showToast("Ocorreu um erro");
      this.controller.resumeCamera();
    }
  }
```

That TimerStream is a workaround, because pauseCamera() did not return any feedback.

**Comment by juliansteenbakker** [comment] 2020-12-21 21:21
Duplicate of #11. There is a fix in that thread.

**Closed by juliansteenbakker** 2020-12-21 21:21 UTC
