### ISSUE TITLE
Could you add a function that scan a photo from gallery

### ISSUE THREAD

**Issue by luckysmg** [juliuscanute/qr_code_scanner#51] opened 2019-10-18 05:52 UTC

**Comment by mx4g** [comment] 2019-10-22 03:28
+1

**Comment by Zanblade** [comment] 2020-07-18 06:09
Would really like to see this implemented, current not sure how to do it without

**Comment by rsaf** [comment] 2020-11-13 11:14
+1

**Comment by wem2017** [comment] 2020-11-30 03:47
+1

**Comment by juliansteenbakker** [comment] 2020-12-10 18:22
This is a duplicate of #37 . Please see that issue for further development.

**Closed by juliansteenbakker** 2020-12-10 18:22 UTC
Labels: enhancement
