### ISSUE TITLE
[BUG] Camera feed not appearing after first load

### ISSUE THREAD

**Issue by danagbemava** [juliuscanute/qr_code_scanner#277] opened 2021-03-09 11:13 UTC
**Describe the bug**
I am experiencing an issue whereby if I load the QRScanner view, the camera opens but the feed from the camera isn't displayed unless the screen locks and reopens.

**Flutter information**
Always provide the output of `flutter doctor -v` as it is needed in order to know on which Flutter versions the bug exists in.

<details>
<summary>flutter doctor -v</summary>

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GH)
    • Flutter version 1.22.6 at /Users/admin/dev/flutter
    • Framework revision 9b2d32b605 (7 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64 • Android 10 (API 29)
    ! Error: Nexus’ IPhone is busy: Waiting for Device. Xcode will continue when Nexus’ IPhone is finished. (code -10)

! Doctor found issues in 1 category.

</details>

**Device (please complete the following information):**
 - Device: Poco X3 NFC, OnePlus Nord
 - OS: MIUI 12.0.8, Android 11

**Screenshots**
On open ![Screenshot_2021-03-09-11-01-41-364_com.Distribution.SwiftRecon.jpg](https://user-images.githubusercontent.com/52815643/110462424-95cd3400-80c8-11eb-9930-a7ed25095c14.jpg)

After lock and unlock
![Screenshot_2021-03-09-11-01-54-802_com.Distribution.SwiftRecon.jpg](https://user-images.githubusercontent.com/52815643/110462455-9e256f00-80c8-11eb-897a-bb199f3eb67d.jpg)

**Additional context**
I noticed this line in the debug log, not sure if it has any bearing on the problem at hand.
`W/PlatformViewsController(11402): Creating a virtual display of size: [1080, 2296] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2205].`

Edit: added screenshots

**Comment by steve3d** [comment] 2021-03-10 06:19
I also have this problem, now waiting for a fix.

**Comment by juliansteenbakker** [comment] 2021-03-10 07:37
> W/PlatformViewsController(11402): Creating a virtual display of size: [1080, 2296] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2205].

By the look of it it seems that the virtual display wants to render with the full width, including the android navigation bar. Can you try hiding the navigation bar and check if that resolves the issue? If that is the case, we need to find a way to detect this navigation bar.

**Comment by steve3d** [comment] 2021-03-10 08:44
this also happens when the scaffold don't have any nav bar, 

in my app, the scaffold only have one child: Stack, the lowest widget is camera view, and it's size are set by MediaQuery.size. on some android devices, this black screen still happens.

**Comment by danagbemava** [comment] 2021-03-10 09:03
> > W/PlatformViewsController(11402): Creating a virtual display of size: [1080, 2296] may result in problems([flutter/flutter#2897](https://github.com/flutter/flutter/issues/2897) is larger than the device screen size: [1080, 2205].
> 
> By the look of it it seems that the virtual display wants to render with the full width, including the android navigation bar. Can you try hiding the navigation bar and check if that resolves the issue? If that is the case, we need to find a way to detect this navigation bar.

Even after hiding the navigation bar, the issue still persists. So I don't think it has any bearing on the issue at hand.
![flutter_02](https://user-images.githubusercontent.com/52815643/110603780-4ac22800-817f-11eb-9347-28e68535a314.png)

**Comment by steve3d** [comment] 2021-03-10 09:08
and this only happens on some android devices, not all.

**Comment by slorop41314** [comment] 2021-03-10 10:27
Same issue here as well, found on Vivo (android) phone

**Comment by juliansteenbakker** [comment] 2021-03-10 10:29
Does this also happen with the example app? I'm trying to reproduce this behaviour.

**Comment by slorop41314** [comment] 2021-03-10 10:35
In my case, the issue appear sometimes (randomly), not every time, still not know how to reproduce

**Comment by Pavlouha** [comment] 2021-03-10 12:56
Same happened on Galaxy s10e (Android 11)

**Comment by juliansteenbakker** [comment] 2021-03-10 13:14
I can't seem to reproduce this. It would be great if someone could provide some sample code to reproduce this.

**Comment by Pavlouha** [comment] 2021-03-10 13:22
> I can't seem to reproduce this. It would be great if someone could provide some sample code to reproduce this.

```dart
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';

void main() => runApp(MaterialApp(home: QRViewExample()));

class QRViewExample extends StatefulWidget {
  const QRViewExample({
    Key key,
  }) : super(key: key);

  @override
  State<StatefulWidget> createState() => _QRViewExampleState();
}

class _QRViewExampleState extends State<QRViewExample> {
  Barcode result;
  QRViewController controller;
  final GlobalKey qrKey = GlobalKey(debugLabel: 'QR');

  // In order to get hot reload to work we need to pause the camera if the platform
  // is android, or resume the camera if the platform is iOS.
  @override
  void reassemble() {
    super.reassemble();
    if (Platform.isAndroid) {
      controller.pauseCamera();
    }
    controller.resumeCamera();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          Expanded(flex: 4, child: _buildQrView(context)),
          Expanded(
            flex: 1,
            child: FittedBox(
              fit: BoxFit.contain,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: <Widget>[
                  if (result != null)
                    Text(
                        'Barcode Type: ${describeEnum(result.format)}   Data: ${result.code}')
                  else
                    Text('Scan a code'),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: <Widget>[
                      Container(
                        margin: EdgeInsets.all(8),
                        child: ElevatedButton(
                            onPressed: () async {
                              await controller?.toggleFlash();
                              setState(() {});
                            },
                            child: FutureBuilder(
                              future: controller?.getFlashStatus(),
                              builder: (context, snapshot) {
                                return Text('Flash: ${snapshot.data}');
                              },
                            )),
                      ),
                      Container(
                        margin: EdgeInsets.all(8),
                        child: ElevatedButton(
                            onPressed: () async {
                              await controller?.flipCamera();
                              setState(() {});
                            },
                            child: FutureBuilder(
                              future: controller?.getCameraInfo(),
                              builder: (context, snapshot) {
                                if (snapshot.data != null) {
                                  return Text(
                                      'Camera facing ${describeEnum(snapshot.data)}');
                                } else {
                                  return Text('loading');
                                }
                              },
                            )),
                      )
                    ],
                  ),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: <Widget>[
                      Container(
                        margin: EdgeInsets.all(8),
                        child: ElevatedButton(
                          onPressed: () async {
                            await controller?.pauseCamera();
                          },
                          child: Text('pause', style: TextStyle(fontSize: 20)),
                        ),
                      ),
                      Container(
                        margin: EdgeInsets.all(8),
                        child: ElevatedButton(
                          onPressed: () async {
                            await controller?.resumeCamera();
                          },
                          child: Text('resume', style: TextStyle(fontSize: 20)),
                        ),
                      )
                    ],
                  ),
                ],
              ),
            ),
          )
        ],
      ),
    );
  }

  Widget _buildQrView(BuildContext context) {
    // For this example we check how width or tall the device is and change the scanArea and overlay accordingly.
    var scanArea = (MediaQuery.of(context).size.width < 400 ||
        MediaQuery.of(context).size.height < 400)
        ? 150.0
        : 300.0;
    // To ensure the Scanner view is properly sizes after rotation
    // we need to listen for Flutter SizeChanged notification and update controller
    return QRView(
      key: qrKey,
      onQRViewCreated: _onQRViewCreated,
      overlay: QrScannerOverlayShape(
          borderColor: Colors.red,
          borderRadius: 10,
          borderLength: 30,
          borderWidth: 10,
          cutOutSize: scanArea),
    );
  }

  void _onQRViewCreated(QRViewController controller) {
    setState(() {
      this.controller = controller;
    });
    controller.scannedDataStream.listen((scanData) {
      setState(() {
        result = scanData;
      });
      Navigator.pushAndRemoveUntil(context,
          MaterialPageRoute(builder: (context) => QRViewExample()),
              (route) => false);
    });
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }
}
```

**Comment by slorop41314** [comment] 2021-03-10 13:24
Yaa i also feel sorry cause it not happen on my phone, it happens on my user's phone and can't reproduce it too.
The code i used almost same as the example.

Is it possible related to android 11? Cause two person above also reporting due to android 11? @juliansteenbakker

**Comment by slorop41314** [comment] 2021-03-10 13:27
Thanks a lot man, great package btw!

**Comment by Amazing-Aidan** [comment] 2021-03-11 15:35
> I have an prefixIcon in a textFormField and use that to navigate to the QR scanner view, it seems like that's causing some interference

I've found the same with a suffixIcon. When I created a button and launched the QRpage from a button, I didn't have a problem. I could click the button a number of times and no bug.

**Entering a TextField**, even without typing, and then launch the QR camera page causes a that the view won't display! 

[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale en-GB)
[√] Android Studio (version 4.1.0)

**Comment by juliansteenbakker** [comment] 2021-03-12 08:03
> Further investigation seems to tie the suggestions above together. **It's the keyboard on display** is reducing the screen size and the view doesn't like that.

If this is the issue, i think you can try disabling resizing the view when keyboard is shown like described here: https://github.com/juliuscanute/qr_code_scanner/issues/128#issuecomment-758892418

> You can add resizeToAvoidBottomInset: false to the Scaffold that the QRView is in to fix this issue. I think the problem is that the qrview is resizing even when you're on another page, which the internal framework cant handle well.

**Comment by steve3d** [comment] 2021-03-12 10:38
No, this also happens on Android 10. some of my app users who using android 10 also reports this black screen problem.

![5BF6DB006C1626DCABBA46166E817858](https://user-images.githubusercontent.com/670687/110928728-27a39e00-8362-11eb-9ad7-3f6163dc8075.jpg)

**Comment by juliansteenbakker** [comment] 2021-03-12 11:04
The issue is that the keyboard is retracting when you open the QRCode view. This causes problems with the view. There are two options to fix this. The first one is to disable resizing when opening keyboard. This can cause items to appear behind the keyboard. You can fix this by making the page scrollable so that users can scroll while the keyboard is opened. https://github.com/juliuscanute/qr_code_scanner/issues/277#issuecomment-797310500

The second option is to wait till the keyboard is closed.

**Comment by steve3d** [comment] 2021-03-12 11:57
No, my case is different, with my app design, there is no way of open keyboard before showing the camera preview. There is no text input widget, so there is no way to open keyboard.

**Comment by steve3d** [comment] 2021-03-18 15:05
any update on this?

**Comment by kaboc** [comment] 2021-03-19 15:38
Just showing a banner ad using google_mobile_ads stops the camera preview regardless of the keyboard. It appears that the controller of QRView is alive because I can still toggle the flashlight. Every time it is toggled, the preview is updated only for the moment and stops again right away.

**Comment by kaboc** [comment] 2021-03-19 18:02
**Reproducible code**

android/app/src/main/AndroidManifest.xml

```xml
<manifest ...>
   <application ...>

        <!-- omitted -->

        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544~3347511713" />
   </application>
</manifest>
```

android/app/build.gradle

```gradle
    defaultConfig {
        applicationId "..."
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
```

pubspec.yaml

```yaml
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^0.11.0+3
  qr_code_scanner: ^0.4.0-nullsafety.0
```


main.dart

<details>
<summary>Click here to open</summary>

```dart
import 'package:flutter/material.dart';

import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:qr_code_scanner/qr_code_scanner.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: _Qr(),
    );
  }
}

class _Qr extends StatefulWidget {
  const _Qr();

  @override
  _QrState createState() => _QrState();
}

class _QrState extends State<_Qr> {
  final _key = GlobalKey();
  QRViewController _controller;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  void reassemble() {
    super.reassemble();
    _controller.pauseCamera();
    _controller.resumeCamera();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
          child: Scaffold(
            body: QRView(
              key: _key,
              onQRViewCreated: (controller) {
                _controller = controller
                  ..scannedDataStream.listen((scanData) {
                    print(scanData.code);
                  });
              },
            ),
            floatingActionButton: FloatingActionButton(
              child: const Icon(Icons.lightbulb),
              onPressed: () => _controller.toggleFlash(),
            ),
          ),
        ),
        const _Ad(),
      ],
    );
  }
}

class _Ad extends StatefulWidget {
  const _Ad();

  @override
  _AdState createState() => _AdState();
}

class _AdState extends State<_Ad> {
  BannerAd _ad;
  var _isAdLoaded = false;

  @override
  void initState() {
    super.initState();

    MobileAds.instance.initialize();

    _ad = BannerAd(
      adUnitId: 'ca-app-pub-3940256099942544/6300978111',
      size: AdSize.banner,
      request: const AdRequest(),
      listener: AdListener(
        onAdLoaded: (_) {
          setState(() => _isAdLoaded = true);
        },
        onAdFailedToLoad: (_, error) {
          setState(() => _isAdLoaded = false);
        },
      ),
    )..load();
  }

  @override
  void dispose() {
    _ad?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 50.0,
      // Compare by removing this line and then hot reloading the app.
      child: _isAdLoaded ? AdWidget(ad: _ad) : const SizedBox(),
    );
  }
}
```
</details>

**Comment by juliansteenbakker** [comment] 2021-03-22 08:36
> ```yaml
> qr_code_scanner: ^0.4.0-nullsafety.0
> ```

Thanks for your information. I see that you are using 0.4.0-nullsafety.0 which is based on version 0.3.4 which has some bugs. I will make a stable null-safety release this week. 

Can everyone that also has this problem please comment which version of qr_code_scanner they are using? I am still unable to reproduce this behaviour and this makes it very hard for me to debug it. I could not reproduce this error with code from @danagbemava so other code which could reproduce this behaviour is still wanted! Thanks in advance.

**Comment by steve3d** [comment] 2021-03-22 18:23
I have this problem starting from 0.3.2

**Comment by steve3d** [comment] 2021-03-24 08:26
```I/HiTouch_HiTouchSensor( 3171): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector( 3171): onAttached, package=edu.seuarch.bmimobile, windowType=2037, mHiTouchRestricted=true
D/mali_winsys( 3171): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer( 3171): disableOutlineDraw is true
W/System  ( 3171): A resource failed to call release.
I/uarch.bmimobil( 3171): Waiting for a blocking GC ProfileSaver```

```
W/PlatformViewsController(11402): Creating a virtual display of size: [1080, 2296] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2205].
```

here are some relative logs of this problem, the most important thing might be related to the second log.

I have changed my code like this:
```
    return Scaffold(
      body: SafeArea(  // add safe area here
        child: Stack(
          children: [
            QRView(
```


this is caused by the phone's status bar size is dynamic, which belongs to the android theme, this caused screen size to change, after I add an `SafeArea`, this problem is gone.

After I check with other users, I will notify here.

**Comment by kaboc** [comment] 2021-03-25 23:39
@juliansteenbakker 
> I see that you are using 0.4.0-nullsafety.0 which is based on version 0.3.4 which has some bugs. I will make a stable null-safety release this week.

Thank you. I tried the new version 0.4.0, but the issue still exists.

Assuming that the issue is due to rebuilds, it doesn't seem like a very practical solution that users of the package have to do something on their side to suppress them because it is almost impossible; rebuilds are triggered many times by many different causes.

**Comment by apachucy** [comment] 2021-03-26 16:07
I can reproduce the same issue with 0.3.5 & 0.4.0 when I hide & restore view from background Scanner starts to works correctly. 
In logs I can see that onResume is called more than once

**Comment by YongliangDing** [comment] 2021-03-29 05:14
> I can reproduce the same issue with 0.3.5 & 0.4.0 when I hide & restore view from background Scanner starts to works correctly.
> In logs I can see that onResume is called more than once

I/AutoFocusManager(22021): Current focus mode 'auto'; use auto focus? true
D/CameraPreview(22021): resume()
W/CameraPreview(22021): initCamera called twice
D/CameraPreview(22021): resume()
W/CameraPreview(22021): initCamera called twice

**Comment by apachucy** [comment] 2021-03-29 08:10
Hi, did someone found a workaround for this issue?

**Comment by raminsafaei** [comment] 2021-03-31 12:36
I've had this problem as well and managed to fix it by calling dispose on controller before navigating to another screen or calling functions in setState on scanData. Honestly I'm not sure if its actually fixed, but it seems to be

**Comment by matpag** [comment] 2021-05-14 17:08
I had a problem where after founding a barcode and navigating to the next screen, if the user was pressing the back button the qrcode scanner was not working anymore.

I think the main problem from provided sample is due to the fixed `GlobalKey` preventing the Widget to rebuild and re-instantiating the controller. I had to change using a GlobalKey generated at every build to fix this. 
This probably it's not efficient but it's the only thing that worked for me.

The code:
```
class QrCodeScanner extends StatefulWidget {

  @override
  QrCodeScannerState createState() => QrCodeScannerState();

}

class QrCodeScannerState extends State<QrCodeScanner> with RouteAware {

  late RouteObserver routeObserver;

  Barcode? result;
  QRViewController? controller;
  StreamSubscription? subscription;

  @override
  void initState() {
    routeObserver = RouteObserver<PageRoute>();
    super.initState();
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    routeObserver.subscribe(this, ModalRoute.of(context) as PageRoute);
  }

  @override
  void dispose() {
    subscription?.cancel();
    controller?.dispose();
    routeObserver.unsubscribe(this);
    super.dispose();
  }

  // In order to get hot reload to work we need to pause the camera if the platform
  // is android, or resume the camera if the platform is iOS.
  @override
  void reassemble() {
    super.reassemble();
    if (Platform.isAndroid) {
      controller!.pauseCamera();
    }
    controller!.resumeCamera();
  }

  @override
  Widget build(BuildContext context) {
    var scanArea = (MediaQuery.of(context).size.width < 400 ||
            MediaQuery.of(context).size.height < 400)
        ? 150.0
        : 300.0;
    return QRView(
      key: GlobalKey(),
      onQRViewCreated: _onQRViewCreated,
      overlay: QrScannerOverlayShape(
        borderColor: Colors.green,
        borderRadius: 10,
        borderLength: 50,
        borderWidth: 10,
        cutOutSize: scanArea),
    );
  }

  void _onQRViewCreated(QRViewController controller) {
    this.controller = controller;
    subscription = controller.scannedDataStream.listen((scanData) {
      //prevent multiple events to enter callback when we are elaborating one
      if (result == null) {
        result = scanData;
        if (QrCodeChecker.isValid(result.code)) {
         //navigate to next screen 
          navigatorKey.currentState?.pushNamed(Routes.next, 
              arguments: Map<String, dynamic> { qrcode: result.code })
          subscription?.cancel();
          controller.dispose();
        }
        result = null;
      }
    });
  }

  @override
  void didPopNext() {
    setState(() {
      //force widget to re-create when user navigate back
    });
  }

}
```

**Comment by nombrekeff** [comment] 2021-05-21 10:30
> I had a problem where after founding a barcode and navigating to the next screen, if the user was pressing the back button the qrcode scanner was not working anymore.
> 
> I think the main problem from provided sample is due to the fixed `GlobalKey` preventing the Widget to rebuild and re-instantiating the controller. I had to change using a GlobalKey generated at every build and adding a callback to didPopNext to fix this.


This did the job for me! Don't know if it will have any other impact though!

**Comment by kaboc** [comment] 2021-06-02 10:34
https://github.com/googleads/googleads-mobile-flutter/issues/32#issuecomment-802327886

I found this is related to the issue below that I reported about two months ago.

> Just showing a banner ad using google_mobile_ads stops the camera preview

Replacing "virtual display" with "hybrid composition" in this package worked for me. It may resolve some other issues too, but I'm not sure about it. I'm hoping that just changing it results in closing many of the existing issues.

It'll be important to carefully consider whether hybrid composition should be used because it appears to have negative impacts on performance.

> Hybrid composition requires Flutter 1.22 (version 1.22.2 is recommended). This mode appends the native android.view.View to the view hierarchy. Therefore, keyboard handling, and accessibility work out of the box. Prior to Android 10, this mode might significantly reduce the frame throughput (FPS) of the Flutter UI. See performance for more info.

https://flutter.dev/docs/development/platform-integration/platform-views#android

**Comment by juliansteenbakker** [comment] 2021-06-25 06:29
I have released 1.0.0-alpha-1 with MLKit support. This framework doesn't use virtual display but rather an openGL texture. I don't think this issue will occur with MLKit.

**Closed by juliansteenbakker** 2021-06-25 06:29 UTC
Labels: bug

**Comment by Vanessa-Berazategui** [comment] 2021-11-12 21:58
> I had a problem where after founding a barcode and navigating to the next screen, if the user was pressing the back button the qrcode scanner was not working anymore.
> 
> I think the main problem from provided sample is due to the fixed `GlobalKey` preventing the Widget to rebuild and re-instantiating the controller. I had to change using a GlobalKey generated at every build and adding a callback to didPopNext to fix this. This probably it's not efficient but it's the only thing that worked for me.
> 
> The code, library version `^0.4.0`:
> 
> ```
> class QrCodeScanner extends StatefulWidget {
> 
>   @override
>   QrCodeScannerState createState() => QrCodeScannerState();
> 
> }
> 
> class QrCodeScannerState extends State<QrCodeScanner> with RouteAware {
> 
>   late RouteObserver routeObserver;
> 
>   Barcode? result;
>   QRViewController? controller;
>   StreamSubscription? subscription;
> 
>   @override
>   void initState() {
>     routeObserver = RouteObserver<PageRoute>();
>     super.initState();
>   }
> 
>   @override
>   void didChangeDependencies() {
>     super.didChangeDependencies();
>     routeObserver.subscribe(this, ModalRoute.of(context) as PageRoute);
>   }
> 
>   @override
>   void dispose() {
>     subscription?.cancel();
>     controller?.dispose();
>     routeObserver.unsubscribe(this);
>     super.dispose();
>   }
> 
>   // In order to get hot reload to work we need to pause the camera if the platform
>   // is android, or resume the camera if the platform is iOS.
>   @override
>   void reassemble() {
>     super.reassemble();
>     if (Platform.isAndroid) {
>       controller!.pauseCamera();
>     }
>     controller!.resumeCamera();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     var scanArea = (MediaQuery.of(context).size.width < 400 ||
>             MediaQuery.of(context).size.height < 400)
>         ? 150.0
>         : 300.0;
>     return QRView(
>       key: GlobalKey(),
>       onQRViewCreated: _onQRViewCreated,
>       overlay: QrScannerOverlayShape(
>         borderColor: Colors.green,
>         borderRadius: 10,
>         borderLength: 50,
>         borderWidth: 10,
>         cutOutSize: scanArea),
>     );
>   }
> 
>   void _onQRViewCreated(QRViewController controller) {
>     this.controller = controller;
>     subscription = controller.scannedDataStream.listen((scanData) {
>       //prevent multiple events to enter callback when we are elaborating one
>       if (result == null) {
>         result = scanData;
>         if (QrCodeChecker.isValid(result.code)) {
>          //navigate to next screen 
>           navigatorKey.currentState?.pushNamed(Routes.next, 
>               arguments: Map<String, dynamic> { qrcode: result.code })
>           subscription?.cancel();
>           controller.dispose();
>         }
>         result = null;
>       }
>     });
>   }
> 
>   @override
>   void didPopNext() {
>     setState(() {
>       //force widget to re-create when user navigate back
>     });
>   }
> 
> }
> ```

I've got the same issue when I click the android back button with qr_code_scanner: ^0.3.5 . 
I've tried to re-create qrview, push remove until and create the scanner page widget again, pause camera and resume it and always the preview image gets frozen.

**Comment by holailusoria** [comment] 2021-12-09 19:15
version 0.5.2 The problem is still present

**Comment by Sabahat06** [comment] 2022-02-03 08:04
Version 0.6.1 The problem is still there

**Comment by Sabahat06** [comment] 2022-02-03 08:04
Version 0.6.1 The problem is still there

**Comment by OFD16** [comment] 2022-07-03 21:29
This problem still persists. Is there a solution to the problem? If so, what is it? (qr_code_scanner 1.0.0)
[BUG] Camera feed not appearing after first load](https://github.com/juliuscanute/qr_code_scanner/issues/277#)
#277

**Comment by m1narulal1** [comment] 2022-07-07 05:17
void _onQRViewCreated(QRViewController controller) {
    setState(() {
      this.controller = controller;
      controller.resumeCamera();
    });
    controller.scannedDataStream.listen((scanData) {
      controller.dispose();
      result = scanData;
      describeEnum(result!.format);
      print("printing result" + result!.code!.toString().substring(5));

      Navigator.pushAndRemoveUntil(
        widget.parentContext,
        MaterialPageRoute(
          builder: (BuildContext context) => HomeScreen(
              selectedIndex: 0, code: result!.code.toString().substring(5)),
        ),
        (route) => false,
      );
    });
  }
Solved My issue. It will work for everyone. Just add controller.resumeCamera(); after declaring Controller. Let me know if problem still arise.

**Comment by butterflyXX** [comment] 2022-08-15 08:19
@m1narulal1 good, its working, I think some Android device need manual open the Camera,if don't
 set resumeCamera,and touch the black screen once,its also working

**Comment by Samuelungbede1** [comment] 2022-08-20 07:52
> void _onQRViewCreated(QRViewController controller) { setState(() { this.controller = controller; controller.resumeCamera(); }); controller.scannedDataStream.listen((scanData) { controller.dispose(); result = scanData; describeEnum(result!.format); print("printing result" + result!.code!.toString().substring(5)); } Solved My issue. It will work for everyone. Just add controller.resumeCamera(); after declaring Controller. Let me know if problem still arise.

This works for me, however, there is still an issue, the camera comes up and remains static, in other words the preview is stagnant

**Comment by Uttkarsh-raj** [comment] 2022-09-19 05:13
> This problem still persists. Is there a solution to the problem? If so, what is it? (qr_code_scanner 1.0.0) [BUG] Camera feed not appearing after first load](#277) #277

Try this, it worked out for me for  qr_code_scanner: ^1.0.1,
  void onQRViewCreated(QRViewController controller) {
    setState(() {
      this.controller = controller;
      controller.resumeCamera();
    });
    controller.scannedDataStream.listen((barcode) => controller.dispose());
  }
}

**Comment by dhruv061** [comment] 2022-10-14 09:55
Thank You! That's working for me!

**Comment by m1narulal1** [comment] 2022-10-14 09:57
> Thank You! That's working for me!

With Pleasure.

**Comment by sushantmzjn** [comment] 2022-12-05 17:07
try this it worked out for me

 @override
  Widget build(BuildContext context) {
    if (controller != null && mounted) {
      controller!.pauseCamera();
      controller!.resumeCamera();
    }

**Comment by fernandozarco** [comment] 2023-06-01 15:54
> > This problem still persists. Is there a solution to the problem? If so, what is it? (qr_code_scanner 1.0.0) [BUG] Camera feed not appearing after first load](#277) #277
> 
> Try this, it worked out for me for qr_code_scanner: ^1.0.1,
> 
> void onQRViewCreated(QRViewController controller) { setState(() => this.controller = controller); controller.scannedDataStream.listen((barcode) => setState((() { this.barcode = barcode; controller.dispose(); }))); setState(() { controller.resumeCamera(); }); }
> 
> and before build context Widget i.e. before Scaffold:
> 
> @OverRide void initState() { super.initState(); }
> 
> @OverRide void dispose() { controller?.dispose(); super.dispose(); }
> 
> @OverRide void reassemble() async { super.reassemble(); if (Platform.isAndroid) { await controller!.pauseCamera(); } await controller!.resumeCamera(); } I think this should solve your error.

Thanks a lot! It works for me.
