### ISSUE TITLE
[BUG] android  - cutOutBottomOffset

### ISSUE THREAD

**Issue by jahnli** [juliuscanute/qr_code_scanner#444] opened 2021-10-20 11:40 UTC
**Describe the bug**

The cutOutBottomOffset does not work, causing the scanning area under Android to remain the center of the screen  

**Flutter information**
![image](https://user-images.githubusercontent.com/20943608/138086146-e14a88df-e139-4fba-8341-0409cee073c5.png)

**Device (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS15]

**Screenshots**

**Additional context**

**Comment by juliansteenbakker** [comment] 2021-11-16 19:58
Duplicate of #385

**Closed by juliansteenbakker** 2021-11-16 19:58 UTC
Labels: bug, android
